version: "3.7"
services:
  user-service:
    env_file:
      - dev.env
    volumes:
      - ./compose-output/us:/usr/src/app/output
      - ./tools/wait-for-it.sh:/wait-for-it.sh
    command: ["/wait-for-it.sh", "rabbitmq:5672", "-t", "60", "--", "node", "dist/apps/user-service/main"]
    ports:
      - 38080:8080

  search-queue-manager:
    env_file:
      - dev.env
    volumes:
      - ./compose-output/sqm:/usr/src/app/output
      - ./tools/wait-for-it.sh:/wait-for-it.sh
    command: ["/wait-for-it.sh", "rabbitmq:5672", "-t", "60", "--", "node", "dist/apps/search-queue-manager/main"]
    ports:
      - 38081:8080

  data-collector:
    env_file:
      - dev.env
    volumes:
      - ./compose-output/dc:/usr/src/app/output
      - ./tools/wait-for-it.sh:/wait-for-it.sh
    command: ["/wait-for-it.sh", "rabbitmq:5672", "-t", "60", "--", "node", "dist/apps/data-collector/main"]

  search-result-calculator:
    env_file:
      - dev.env
    environment:
      LOG_LEVEL: info
    volumes:
      - ./compose-output/src:/usr/src/app/output
      - ./tools/wait-for-it.sh:/wait-for-it.sh
    command: ["/wait-for-it.sh", "rabbitmq:5672", "-t", "60", "--", "node", "dist/apps/search-result-calculator/main"]

  search-result-aggregator:
    env_file:
      - dev.env
    volumes:
      - ./compose-output/sra:/usr/src/app/output
      - ./tools/wait-for-it.sh:/wait-for-it.sh
    command: ["/wait-for-it.sh", "rabbitmq:5672", "-t", "60", "--", "node", "dist/apps/search-result-aggregator/main"]

  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: dev
      RABBITMQ_DEFAULT_PASS: dev
    volumes:
    - ./backend/mq/rmq-definitions.json:/etc/rabbitmq/definitions.json
    ports:
      - 15672:15672
      - 5672:5672

  mongo:
    image: mongo
    ports:
      - 27017:27017

  firestore:
    build:
      context: ./db/firestore
    ports:
      - 8555:8080

#  cassandra:
#    build:
#      context: ./db/cassandra
#    ports:
#      - 9042:9042
