package com.kingboo.dataaggregator.model

enum class InboundMqMessagePattern {
    USER_SEARCH_REQUEST_CREATED,
    USER_SEARCH_REQUEST_UPDATED,
    USER_SEARCH_REQUEST_DELETED,
    CYCLIC_SEARCH_REQUEST_CREATED,
    CYCLIC_SEARCH_REQUEST_DELETED,
    HOTELS_COLLECTION_COMPLETED,
    HOTELS_PROCESSING_COMPLETED
}
