spring:
  rabbitmq:
    addresses: ${MQ_ADDRESS:amqp://dev:dev@localhost:5672}
  cloud:
    gcp:
      project-id: ${FIRESTORE_PROJECT_ID:dev}
      firestore:
        emulator:
          enabled: true
        host-port: localhost:8555
    #      credentials:
    #        encoded-key: ${FIRESTORE_ENCODED_KEY}
    stream:
      bindings:
        processMessage-in-0:
          group: user-notifications
        processMessage-out-0:
          destination:
          group: user-notifications-abc
      rabbit:
        bindings:
          processMessage-in-0:
            consumer:
              queueNameGroupOnly: true
              declareExchange: false
              bindQueue: false
          processMessage-out-0:
            producer:
              queueNameGroupOnly: true
              bindQueue: false
              routingKeyExpression: '''user-notifications-abc'''

logging:
  level:
    com:
      # mute `default credentials provider missing` error when using emulator
      google.cloud.spring.core.DefaultCredentialsProvider: off
