service: user-service
runtime: nodejs14
instance_class: F1
env_variables:
  NODE_ENV: prod
  PORT: 8080
  LOG_LEVEL: debug
  APP_LABEL: US
  CORS_ORIGINS: "__CORS_ORIGINS__"
  LOG_COLLECTOR_TOKEN: "__LOG_COLLECTOR_TOKEN__"
  FIRESTORE_PROJECT_ID: "__FIRESTORE_PROJECT_ID__"
  MQ_ADDRESS: "__MQ_ADDRESS__"
  MQ_USER_NOTIFICATIONS_QUEUE_NAME: user-notifications
  MQ_USER_NOTIFICATIONS_QUEUE_MESSAGE_TTL: 60000
  SEARCH_REQUESTS_RESOURCE_ADDRESS: "__SEARCH_REQUESTS_RESOURCE_ADDRESS__"

automatic_scaling:
  min_instances: 0
  max_instances: 1
  target_cpu_utilization: 0.9
  target_throughput_utilization: 0.9
