# TODO: change CORS_ORIGINS env

runtime: nodejs12
default_expiration: "10m"
handlers:
  - url: /favicon\.ico
    secure: always
    redirect_http_response_code: 301
    static_files: public/favicon.ico
    upload: public/favicon\.ico

  - url: /
    secure: always
    redirect_http_response_code: 301
    static_files: public/index.html
    upload: public/index.html

  - url: /public
    secure: always
    redirect_http_response_code: 301
    static_dir: public

  - url: /socket\.io/.*
    secure: always
    script: auto

  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto

