version: "3.7"
services:
  data-collector:
    env_file:
      - westus01.env
      - ./../opc.env
    volumes:
      - ./../../../compose-output:/usr/src/app/dist/apps/data-collector/output
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 60s
