version: "3.7"
services:
  data-collector:
    env_file:
      - westus01.env
      - ./../opc.env
    volumes:
      - ./../../../compose-output:/usr/src/app/dist/apps/data-collector/output

#  filebeat:
#    env_file:
#      - westus01.env
#    volumes:
#      - filebeat.yml:/etc/filebeat/filebeat.yml:ro
#      - ./../../../compose-output:/var/log/apps:ro
