version: "3.7"
services:
  data-collector:
    env_file:
      - westus01.env
      - ./../opc.env
    volumes:
      - ./../../../compose-output:/usr/src/app/dist/apps/data-collector/output

  filebeat:
    image: docker.elastic.co/beats/filebeat-oss:7.12.0
    # needs to override config file
    command: filebeat -e -strict.perms=false
    env_file:
      - westus01.env
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./../../../compose-output:/var/log/apps:ro
