export enum DataCollectionNotificationsMessagePattern {
  NEW_SCENARIO = 'NEW_SCENARIO',
  SEARCH_PLACE_COLLECTION_COMPLETED = 'SEARCH_PLACE_COLLECTION_COMPLETED',
  HOTELS_COLLECTION_COMPLETED = 'HOTELS_COLLECTION_COMPLETED',
}
