export enum DataUpdatesMessagePattern {
  SEARCH_REQUEST_DELETED = 'SEARCH_REQUEST_DELETED',
  HOTELS_PROCESSING_COMPLETED = 'HOTELS_PROCESSING_COMPLETED',
  PLACE_PROCESSING_COMPLETED = 'PLACE_PROCESSING_COMPLETED',
}
