export enum UserNotificationsMessagePattern {
  SEARCH_REQUEST_CREATED = 'SEARCH_REQUEST_CREATED',
  SEARCH_REQUEST_UPDATED = 'SEARCH_REQUEST_UPDATED',
  SEARCH_REQUEST_DELETED = 'SEARCH_REQUEST_DELETED',
  CYCLIC_SEARCH_REQUEST_CREATED = 'CYCLIC_SEARCH_REQUEST_CREATED',
  CYCLIC_SEARCH_REQUEST_DELETED = 'CYCLIC_SEARCH_REQUEST_DELETED',
  HOTELS_COLLECTION_COMPLETED = 'HOTELS_COLLECTION_COMPLETED',
  TOP_HOTELS_UPDATED = 'TOP_HOTELS_UPDATED',
}
