version: "3.7"
services:
  search-queue-manager:
    volumes:
      - ./../../../compose-output/sqm:/usr/src/app/output
    env_file:
      - westus00.env
      - ./../opc.env
    ports:
      - 8081:8080

  search-result-calculator:
    env_file:
      - westus00.env
      - ./../opc.env
    environment:
      LOG_LEVEL: info
    volumes:
      - ./../../../compose-output/src:/usr/src/app/output

  search-result-aggregator:
    env_file:
      - westus00.env
      - ./../opc.env
    volumes:
      - ./../../../compose-output/sra:/usr/src/app/output

  filebeat:
    image: docker.elastic.co/beats/filebeat-oss:7.12.0
    # needs to override config file
    command: filebeat -e -strict.perms=false
    env_file:
      - westus00.env
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./../../../compose-output/sqm/logs:/var/log/apps/sqm:ro
      - ./../../../compose-output/src/logs:/var/log/apps/src:ro
      - ./../../../compose-output/sra/logs:/var/log/apps/sra:ro
