version: "3.7"
services:
  search-queue-manager:
    volumes:
      - ./../../../compose-output:/usr/src/app/dist/apps/search-queue-manager/output
    env_file:
      - westus00.env
      - ./../opc.env
    ports:
      - 8081:8080
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 60s

  search-result-calculator:
    env_file:
      - westus00.env
      - ./../opc.env
    volumes:
      - ./../../../compose-output:/usr/src/app/dist/apps/search-result-calculator/output
    ports:
      - 8082:8080
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 60s
