name: Deploy webapp
on:
  push:
    branches:
      - master
      - develop
    paths:
      - 'webapp/**'
      - 'cloud/gcp/webapp/**'
      - '.github/workflows/deploy-webapp.yml'

jobs:
  deploy_webapp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Use cache
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-webapp-ci-${{ hashFiles('webapp/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-webapp-ci-

      - name: Install dependencies
        working-directory: ./webapp
        run: |
          npm ci --silent

      - name: Build package ready for gcp
        working-directory: ./webapp
        env:
          NODE_ENV: 'production'
          REACT_APP_USER_SERVICE_ADDRESS: ''
        run: |
          npm run build
          mv build/* ../cloud/gcp/webapp/public

      - name: GCP authenticate as service account
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy to app engine
        working-directory: ./cloud/gcp/webapp
        run: |
          gcloud -q app deploy -v $GITHUB_SHA
