name: e2e tests
on:
  push:
    branches:
      - add-test-framework
    paths:
      - 'backend/**'
      - 'test-framework/**'
      - '.github/workflows/e2e-tests.yml'
  pull_request:
    branches:
      - master

jobs:
  local_registry:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host

      - name: Build and push to local registry
        uses: docker/build-push-action@v2
        with:
          context: ${{GITHUB_WORKSPACE}}/backend
          file: kb-data-collector.Dockerfile
          push: true
          tags: localhost:5000/piotrwest/kb-data-collector:test

      - name: Inspect
        run: |
          docker buildx imagetools inspect localhost:5000/piotrwest/kb-data-collector:test

#  publish_data-collector:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v1
#
#      # takes branch name as a tag
#      # in case of master takes 'latest'
#      # in case of PR takes $GITHUB_SH
#      - name: Publish data-collector to registry
#        uses: elgohr/Publish-Docker-Github-Action@master
#        with:
#          name: piotrwest/kb-data-collector
#          username: ${{ secrets.DOCKER_USER }}
#          password: ${{ secrets.DOCKER_PASS }}
#          workdir: backend
#          dockerfile: kb-data-collector.Dockerfile
#
#  run_data-collector_e2e:
#    runs-on: ubuntu-latest
#    needs: [publish_data-collector]
#    services:
#      rabbitmq:
#        image: rabbitmq:3-management-alpine
#        env:
#          RABBITMQ_DEFAULT_USER: dev
#          RABBITMQ_DEFAULT_PASS: dev
#        volumes:
#          - ./backend/mq/rmq-definitions.json:/etc/rabbitmq/definitions.json
#        ports:
#          - 15672:15672
#          - 5672:5672
#
#      firebase-test:
#        image:
#
#      mongo:
#        image: mongo
#        ports:
#          - 27017:27017
#
#      data-collector:
#        image: piotrwest/kb-data-collector:${{github.sha}}
#        env:
#          NODE_ENV: dev
#          PORT: 8080
#          LOG_LEVEL: debug
#          MONGO_ADDRESS: mongodb://mongo:27017/dev
#          FIRESTORE_PROJECT_ID: dev
#          FIRESTORE_EMULATOR_HOST: firestore
#          FIRESTORE_EMULATOR_PORT: 8080
#          MQ_ADDRESS: amqp://dev:dev@rabbitmq:5672
#          MQ_COLLECTING_SCENARIO_QUEUE_NAME: collecting-scenario
#          MQ_DATA_COLLECTION_NOTIFICATIONS_QUEUE_NAME: data-collection-notifications
#          MQ_DATA_TO_PROCESS_QUEUE_NAME: data-to-process
#        ports:
#          - 8080:8080
#
#    steps:
#      - uses: actions/checkout@v2
