name: Plan infrastructure on westus02
on:
  pull_request:
    branches:
      - main

jobs:
  validate_terraform:
    env:
      tf_actions_working_dir: ./cloud/gcp/westus02/terraform
      TF_VAR_project: ${{ secrets.GCLOUD_PROJECT }}
      TF_VAR_region: us-east1
      TF_VAR_zone: us-east1-b
      TF_VAR_vm_name: vm-instance
      TF_VAR_github-service_name: ${{ secrets.WESTUS02_USER }}
      TF_VAR_github-service_pub_key: ${{ secrets.WESTUS02_PUBLIC_KEY }}
      TF_VAR_gservice_email: ${{ secrets.GCP_SA_EMAIL }}

    defaults:
      run:
        working-directory: ${{ env.tf_actions_working_dir }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: GCP authenticate as service account
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCLOUD_PROJECT }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - uses: hashicorp/setup-terraform@v1

      - name: Terraform format
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init -input=false

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -input=false -out=westus02.tfplan
        continue-on-error: true

      - name: Attach comment with tf result to PR
        uses: actions/github-script@0.9.0
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`

            <details><summary>Show Plan</summary>

            \`\`\`\n
            ${process.env.PLAN}
            \`\`\`

            </details>

            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ env.tf_actions_working_dir }}\`, Workflow: \`${{ github.workflow }}\`*`;

            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Archive terraform plan
        if: ${{ steps.plan.outcome == 'success' }}
        uses: actions/upload-artifact@v2
        with:
          name: westus02-tf
          path: |
            ${{env.tf_actions_working_dir}}/westus02.tfplan
            ${{env.tf_actions_working_dir}}/.terraform
            ${{env.tf_actions_working_dir}}/.terraform.lock.hcl
          if-no-files-found: error

      - name: Fail when tf plan failure
        if: ${{ steps.plan.outcome == 'failure' }}
        run: exit 1
