name: Test webapp
on:
  pull_request:
    branches:
      - master

jobs:
  test_webapp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Use cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-webapp-ci-${{ hashFiles('webapp/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-webapp-ci-

      - name: Install dependencies
        working-directory: ./webapp
        run: |
          npm ci --silent

      - name: Build
        working-directory: ./webapp
        env:
          NODE_ENV: 'production'
        run: |
          npm run build

      - name: Test
        working-directory: ./webapp
        env:
          CI: true
        run: |
          echo "there are no tests"
