name: Test backend
on:
  pull_request:
    branches:
      - main

jobs:
  test_backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Use cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-backend-ci-${{ hashFiles('backend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-backend-ci-

      - name: Install dependencies
        working-directory: ./backend
        run: |
          npm ci

      - name: Build user-service
        working-directory: ./backend
        run: |
          npm run build:us

      - name: Build data-collector
        working-directory: ./backend
        run: |
          npm run build:dc

      - name: Build search-queue-manager
        working-directory: ./backend
        run: |
          npm run build:sqm

      - name: Build search-result-calculator
        working-directory: ./backend
        run: |
          npm run build:src

      - name: Test backend
        working-directory: ./backend
        run: |
          npm test
