name: e2e tests
on:
  push:
    branches:
      - main
      - cassandra-poc
    paths:
      - 'backend/**'
      - '.github/workflows/test-data-integration.yml'
  schedule:
    - cron: '0 3,9,15,21 * * *' # run at 3.00, 9.00, 15.00 and 21.00

jobs:
  run_e2e_test:
    runs-on: ubuntu-latest
    services:
      cassandra:
        image: cassandra:latest
        ports:
          - 9042:9042

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - uses: actions/setup-python@v2
        with:
          python-version: '2.7'

      - name: Create cassandra tables
        working-directory: ./db/cassandra
        run: |
          curl https://downloads.datastax.com/enterprise/cqlsh-5.1.tar.gz
          ls -a
          ll
          tar -xzvf cqlsh-5.1.tar.gz
          cqlsh --version
          cqlsh --help
          cqlsh -f ./01_init.cql

      - name: Use cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-backend-ci-${{ hashFiles('backend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-backend-ci-

      - name: Install dependencies
        working-directory: ./backend
        run: |
          npm ci --silent

      - name: Build data-collector
        working-directory: ./backend
        run: |
          npm run build:dc



      - name: Run data integration tests
        working-directory: ./backend
        env:
          NODE_ENV: dev
          CORS_ORIGINS: ''
          ASTRA_CONTACT_POINT: localhost
          MQ_ADDRESS: mock
          MQ_COLLECTING_SCENARIO_QUEUE_NAME: mock
          MQ_DATA_COLLECTION_NOTIFICATIONS_QUEUE_NAME: mock
          MQ_DATA_TO_PROCESS_QUEUE_NAME: mock
        run: |
          npm run e2e:dc
